### ISSUE TITLE
Problem with DeepSpeed for BigBird Sparse

### ISSUE THREAD

**Issue by aaronmaiww** [AIRI-Institute/GENA_LM#12]
Hi,

thank you for this excellent repository! 

I'm trying to set-up `gena-lm-bigbird-base-sparse-t2t`, but I can't install the requisite libraries in the way suggested on huggingface:

```
pip install triton==1.0.0
DS_BUILD_SPARSE_ATTN=1 pip install deepspeed==0.6.0 --global-option="build_ext" --global-option="-j8" --no-cache

```

First, I get  `ERROR: No matching distribution found for triton==1.0.0`, then, when I don't require a specific version of triton, I get another issue when installing deepspeed. Apparently the 'ninja' library cannot be installed.

Thank you for any help, I'd love to fine-tune this model!

**Comment by yurakuratov** [comment]
Hi! 
It seems that triton 1.0.0 requires python 3.9 or lower. I am successfully running our models with python 3.8 and triton 1.0.0. Try to check your python version.
Yes, you would need to install `ninja` before `deepspeed`.

**Comment by yurakuratov** [comment]
You can also try to using triton 1.1.1 as mentioned here:
https://github.com/yurakuratov/t5-experiments#triron-111
but you will need to install deepspeed fork from this instruction.

**Comment by aaronmaiww** [comment]
Thank you for the response, that was helpful! 

(I'm still stuck, probably my fault though. When I try to switch to python 3.9 in google colab, then I can install both trition 1.0.0 and deepspeed, but somehow I can no longer use the transformers module, even when its clearly installed)

**Comment by yurakuratov** [comment]
Could you try to install transformers==4.17.0 with `!pip install transformers==4.17.0`?

**Comment by aaronmaiww** [comment]
Unfortunately, I still get this error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-279c49635b32>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import transformers

ModuleNotFoundError: No module named 'transformers'
```

This problem seems to occur with some other modules such as wandb too, while e.g. numpy and pandas work fine. Do you have any ideas why?

**Comment by yurakuratov** [comment]
Hi, @aaronmaiww! I have just updated readme section on requirements for sparse models: https://github.com/AIRI-Institute/GENA_LM#deepspeed-for-sparse-ops. Hope you find it useful.
