### ISSUE TITLE
Training costs

### ISSUE THREAD

**Issue by chenwydj** [AIRI-Institute/GENA_LM#15]
Dear Authors: May I ask how many (A100) GPU hours will be needed to pretrain GENA-LM?

Thank you very much!

**Comment by yurakuratov** [comment]
Hi!

It takes approximately 5 days to train a base-sized model (110M parameters) using 8 A100 GPUs with a batch size of 256 for 2 million steps. For a larger model (336M parameters), it takes around 7 days to train using 8 A100 GPUs for 1 million steps, also with a batch size of 256.

These estimates are based on our current code base. I believe they could be improved by implementing FlashAttention and other recent speed-up techniques.

**Comment by chenwydj** [comment]
Thanks @yurakuratov !
