### ISSUE TITLE
Questions about the visualization difference between results in the manuscript and reproduced

### ISSUE THREAD

**Issue by HelloWorldLTY** [AIRI-Institute/GENA_LM#19]
Hi, thanks for your great work. I am particually interested in your species classificaiton performance. According to the figure 4a, it seems that different species are well-seperated. 

<img width="406" alt="image" src="https://github.com/user-attachments/assets/89f3a497-096f-4e49-9222-52a6818c2df6">

However, based on my own reproduced results, it seems that some speices do not seperate:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/468f1361-c142-4ff4-b975-b367bd60edc9">

I used the example model to reproduce it. Thanks a lot.

**Comment by alexeyshmelev** [comment]
@HelloWorldLTY, thanks a lot for the question! I've been planning to add code to replicate our image for a while. Check out [this](https://github.com/AIRI-Institute/GENA_LM/blob/main/notebooks/gena_clusterization_example.ipynb) notebook. You will also need [this](https://github.com/AIRI-Institute/GENA_LM/blob/main/notebooks/2023-08-10%2019_40_52.828317species_extended_metadata.csv) file. As a result, you can get almost the same image (selected subsequences from each genome may vary) as the one used in our paper.

Sorry for the delayed reply. Write back if you have any questions.

**Comment by HelloWorldLTY** [comment]
I see, thanks for your information. I think using updated information will be helpful.
