### ISSUE TITLE
Unable to Access Download Link for Promoters on EPD Website

### ISSUE THREAD

**Issue by tinh1115** [AIRI-Institute/GENA_LM#2]
Description:
I am unable to access the download link for promoters (https://epd.epfl.ch/get_promoters.php). Whenever I try to access the link, I am presented with an error message that says "There is an error in the query!".

Additional Information:
I have tried accessing the link from different browsers and devices, but the error persists. I believe this is a problem with the EPD website

**Comment by tinh1115** [comment]
I think I found the workaround, first need to go here: https://epd.epfl.ch/EPDnew_select.php
then fill the form, then it will go the page get_promoters.php to download.

**Comment by yurakuratov** [comment]
Thanks for pointing this out. I have [updated](https://github.com/AIRI-Institute/GENA_LM/commit/f4130884f2b38ea915103156f3879ca165ffb6c4) readme with the correct url.
How to get promoters data was also discussed here: https://github.com/AIRI-Institute/GENA_LM/issues/1
