### ISSUE TITLE
input sequence size

### ISSUE THREAD

**Issue by hhy-joseph** [AIRI-Institute/GENA_LM#4]
This is a great respiratory! Thank you for sharing.
I found in Hugging face, it said input sequence size is about 24000 nucleotides (4096 BPE tokens) compared to 510 nucleotides of DNABERT and 4096 Maximum sequence length; but in github is input sequence size is about 3000 nucleotides (512 BPE tokens) compared to 510 nucleotides of DNABERT.

Might I know which one is the latest one? Input size with 24000 nucleotides is really excited to see!

Thank you!

**Comment by yurakuratov** [comment]
Hi!

Up-to-date information about the GENA-LM models is in the Huggingface Hub. Currently, we have two models in the Huggingface Hub:
- [gena-lm-bert-base](https://huggingface.co/AIRI-Institute/gena-lm-bert-base) - Bert-like architecture with 512 BPE tokens sequence length
- [gena-lm-bigbird-base-t2t](https://huggingface.co/AIRI-Institute/gena-lm-bigbird-base-t2t) - BigBird-like architecture with 4096 BPE tokens sequence length
