### ISSUE TITLE
ENSEMBL version

### ISSUE THREAD

**Issue by agitter** [AIRI-Institute/GENA_LM#6]
Thanks for sharing all these excellent resources alongside your preprint. I'm starting to look through them and wanted to clarify the ENSEMBL version you used.  The FTP links in the tables in this repo indicate release 106, but the preprint text and footnote 2 URL say release 108.

**Comment by labdevgen** [comment]
> Thanks for sharing all these excellent resources alongside your preprint. I'm starting to look through them and wanted to clarify the ENSEMBL version you used. The FTP links in the tables in this repo indicate release 106, but the preprint text and footnote 2 URL say release 108.

The table is correct, we used version 106. We will update the manuscript text, thanks for pointing to this!

**Comment by minjaf** [comment]
> Thanks for sharing all these excellent resources alongside your preprint. I'm starting to look through them and wanted to clarify the ENSEMBL version you used. The FTP links in the tables in this repo indicate release 106, but the preprint text and footnote 2 URL say release 108.

The table is correct, we used version 106. We will update the manuscript text, thanks for pointing to this!
