### ISSUE TITLE
1000G snps data process

### ISSUE THREAD

**Issue by luoshengtangxiademao** [AIRI-Institute/GENA_LM#7]
Hello, the experiment is quite full. But I would like to know what happened to your 1000G SNPs data. Sorry, I can't find the relevant detailed instructions.

**Comment by minjaf** [comment]
Hi!
We have updated the repo to [provide](https://github.com/AIRI-Institute/GENA_LM/tree/main/src/gena_lm/genome_tools) code and provided ReadMe describing how 1000G SNPs information was incorporated in the corpus. Let me know if you have other questions!
