### ISSUE TITLE
how to get the SpliceAI  data from illumina? 

### ISSUE THREAD

**Issue by maris205** [AIRI-Institute/GENA_LM#8]
I visite the SpliceAI web page https://basespace.illumina.com/projects/66029966/about

The web page says "You don't have access to the requested page".

How to get this data?

**Comment by minjaf** [comment]
Hi Maris,

Indeed, Illumina has restricted access to this dataset. However, if you sign up on this web-site (follow "Don't have an account?" link; the registration if free) you will be able to download data.

Please note that we have reprocessed the dataset (original records include 1-hot encoded sequences) without changing its structure. If you want this reprocessed dataset, please contact me and I will organize sharing space.

Best reads,
Venimain
